name: Central Entry Point

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  enforce-repo-name:
    uses: ./.github/workflows/enforce-repo-naming.yml

  enforce-security-checks:
    uses: ./.github/workflows/enforce-security-checks.yml

  # enforce-folder-file-naming:
  #   uses: ./.github/workflows/enforce-folder-file-naming.yml
  
  # update-documentation:
  #   uses: ./.github/workflows/update-documentation.yml
