name: Central Entry Point

on:
  workflow_call:
    inputs:
      slack-token:
        required: false
        type: string
      channel-id:
        required: false
        type: string

jobs:
  enforce-repo-name:
    uses: ./.github/workflows/enforce-repository-name.yml@main

  enforce-security-checks:
    uses: ./.github/workflows/enforce-security-checks.yml@main
    permissions: 
      actions: read
      contents: read
      security-events: write