name: Central Entry Point

on:
  workflow_call:

jobs:
  enforce-repo-name:
    uses: ./enforce-repository-name.yml@main

  enforce-security-checks:
    uses: ./enforce-security-checks.yml@main
    permissions: 
      actions: read
      contents: read
      security-events: write