name: "Enforce Security Checks"

on:
  workflow_call:
    inputs:
      slack-token:
        required: false
        type: string
      channel-id:
        required: false
        type: string

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, phpstan

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHPStan Security Check
        run: vendor/bin/phpstan analyse --level=max


      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'javascript-typescript,c-cpp,actions,go'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Send Slack Notification on Failure
        if: failure()
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: https://api.jubbytech.com/server-github-webhook-processor/enforce-repo-naming-notify.php
          data: '{"title": "Security threat found","text": "Security Vulnerabilities were found while analyzing codebase (Psalm & CodeQL)","repo": "${{ github.event.repository.name }}","format": "", "webhook_secret":""}'