name: "Enforce Security Checks"

on:
  workflow_call:
    inputs:
      slack-token:
        required: false
        type: string
      channel-id:
        required: false
        type: string

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'javascript-typescript,c-cpp,actions,go'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Send Slack Notification on Failure
        if: failure()
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }} # Use a secret!
          data: '{"title": "Security threat found","text": "Security Vulnerabilities were found while analyzing codebase (PHPStan & CodeQL)","repo": "${{ github.event.repository.name }}","format": "", "webhook_secret":""}'