name: Enforce Valid Repository Name

on:
  push:
    branches: ["**"]
    tags: ["**"]

jobs:
  validate-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate Repository Name
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          # Ensure REPO_NAME is set
          if [[ -z "$REPO_NAME" ]]; then
            echo "Error: Repository name is not defined."
            exit 1
          fi

          # Define valid suffixes, projects, and modules
          VALID_SUFFIXES=("backend" "middleware" "frontend" "mobileapp")
          VALID_PROJECTS=("middey" "nellalinksbs" "nellalinktest" "rimplenet")
          VALID_MODULES=("user-app" "admin-app" "kyc-verification" "validate-transaction")

          # Extract parts of the repository name
          SUFFIX=$(echo "$REPO_NAME" | cut -d- -f1)
          PROJECT=$(echo "$REPO_NAME" | cut -d- -f2)
          MODULE=$(echo "$REPO_NAME" | cut -d- -f3-)

          # Validation function
          is_valid() {
            local value="$1"
            shift
            for item in "$@"; do
              if [[ "$item" == "$value" ]]; then
                return 0
              fi
            done
            return 1
          }

          # Validate each part
          if ! is_valid "$SUFFIX" "${VALID_SUFFIXES[@]}"; then
            echo "Error: Invalid suffix '$SUFFIX'. Must be one of: ${VALID_SUFFIXES[@]}."
            exit 1
          fi

          if ! is_valid "$PROJECT" "${VALID_PROJECTS[@]}"; then
            echo "Error: Invalid project name '$PROJECT'. Must be one of: ${VALID_PROJECTS[@]}."
            exit 1
          fi

          if ! is_valid "$MODULE" "${VALID_MODULES[@]}"; then
            echo "Error: Invalid module name '$MODULE'. Must be one of: ${VALID_MODULES[@]}."
            exit 1
          fi

          echo "Repository name '$REPO_NAME' is valid."

      - name: Send Slack Notification on Invalid Repository Name
        if: failure()
        uses: sanjaykrishnanrs/slack-notify-junitxml-action@0.1.0-beta
        with:
          title: Repository Name Validation
          slackbotid: A089R98DLSX
          slackbottoken: xoxb-8328549482453-8316932500135-DC1ZjQM2WH8gnDe43Ko7ZgXt
          slackchannel: '#all-jubbytech'
